### ISSUE TITLE
What does "cap" param limit?

### ISSUE THREAD

**Issue by TheCGDF** [spebern/futures-delay-queue#1]
```
pub fn delay_queue<T: 'static + Send>(
    cap: usize
) -> (DelayQueue<T>, Receiver<T>)
```
doc: This delay queue has a buffer that can hold at most cap messages at a time.

I thought I cannot insert more than "cap", but I tried this:
```
    let (queue, rx) = delay_queue::<i8>(1);
    queue.insert(1, Duration::from_secs(1));
    queue.insert(2, Duration::from_secs(1));
    queue.insert(3, Duration::from_secs(1));
    queue.insert(4, Duration::from_secs(2));
    queue.insert(5, Duration::from_secs(2));
    queue.insert(6, Duration::from_secs(2));
    queue.insert(7, Duration::from_secs(3));
    queue.insert(8, Duration::from_secs(3));
    queue.insert(9, Duration::from_secs(3));
    loop {
        let received = rx.receive().await;
        if received.is_none() {
            break;
        }
        println!("{}", received.unwrap());
    }
```
It worked correctly. So I think I misunderstood the meaning of "cap" parameter.

I looked up the underlying code, but I'm not able to comprehend it completely.

How should I use "cap" correctly?

**Comment by spebern** [comment]
Hi,
I think the documentation here is wrong, I'll change that. The underlying generic channel might or might not use the capacity:
```
    /// Creates a new instance of the Ring Buffer with the given capacity.
    /// `RingBuf` implementations are allowed to ignore the `capacity` hint and
    /// utilize their default capacity.
    fn with_capacity(cap: usize) -> Self;
```
I'll update the documentation here. Thanks!

**Comment by TheCGDF** [comment]
I saw the underlying implementation:
```
    pub fn with_capacity(capacity: usize) -> VecDeque<T> {
        // +1 since the ringbuffer always leaves one space empty
        let cap = cmp::max(capacity + 1, MINIMUM_CAPACITY + 1).next_power_of_two();
        assert!(cap > capacity, "capacity overflow");

        VecDeque {
            tail: 0,
            head: 0,
            buf: RawVec::with_capacity(cap),
        }
    }
```
As per my understanding, the `capacity` hint will be ignored only if capacity<1 ,that is capacity==0.

I also noticed that `fn new_handle_with_future(&self, value: T, dur: Duration)` uses `channel(capacity: 0)`.
```
    pub fn insert(&self, value: T, dur: Duration) -> DelayHandle {
        self.new_handle_with_future(value, dur)
    }

    fn new_handle_with_future(&self, value: T, dur: Duration) -> DelayHandle {
        let (reset_tx, reset_rx) = channel(0);
        ...
    }
```
So I have a guess that `fn insert(&self, value: T, dur: Duration)` will expand capacity automatically when capacity is not enough.

I don't know whether my guess is right, but it sounds a little plausible.

**Comment by spebern** [comment]
I had a closer look and the channel that is used should be:

```
generic_channel::<parking_lot::RawMutex, T, GrowingHeapBuf<T>>
```

And `GrowingHeapBuf` indeed resizes dynamically. I did not look too close
at the code before and expected the behaviour to be similar to Golangs (channel
with 0 capacity blocks on sending until the receiver collects the value).

**Comment by spebern** [comment]
I guess the best way is to provide a delay queue with a fixed buffer and a dynamically growing delay queue. What do you think?

**Comment by TheCGDF** [comment]
I'm not sure but I personally would like to have a dynamic buffer to offload mental burdens.

**Comment by spebern** [comment]
@TheCGDF I removed the `capacity` parameter in the new published version.
